### ISSUE TITLE
Error: sqlite3.InterfaceError: Error binding parameter 25 - probably unsupported type

### ISSUE THREAD

**Issue by shimizurei** [elarkham/VGMdb-BeetsPlug#3]
### Problem
I was trying to add an album and I ended up with the following error: `sqlite3.InterfaceError: Error binding parameter 25 - probably unsupported type`. Verbose code below

```
PS C:\Users\ME> beet -vv import C:\Users\ME\Downloads\Muzik\[TESTOO]
user configuration: C:\Users\ME\AppData\Roaming\beets\config.yaml
data directory: C:\Users\ME\AppData\Roaming\beets
plugin paths: C:\Users\ME\AppData\Roaming\beets\beetsplug
Sending event: pluginload
Querying VGMdb
lyrics: Disabling google source: no API key configured.
inline: adding item field multidisc
library database: C:\Users\ME\AppData\Roaming\beets\beets_musiclibrary.db
library directory: C:\Users\ME\Music
Sending event: library_opened
Sending event: import_begin
Sending event: import_task_created
Sending event: import_task_start
Logged from file importer.py, line 1340
Logged from file match.py, line 414
No album ID found.
Logged from file match.py, line 448
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'ref:rain / \u7729\u3044\u3070\u304b\u308a', 'tracks': u'5', 'artist': u'aimer'}
Requesting MusicBrainz release 2877b5cf-4227-4a8c-a6b3-3318e2511c35
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.04
Requesting MusicBrainz release a7336cd0-3150-476b-a9fa-da1a7c083349
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.13
Requesting MusicBrainz release b80eb50a-5b4b-44d3-a931-292bf078aa5b
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.05
Requesting MusicBrainz release 58ec5e8a-4a84-4d5f-bf35-e179a8261760
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.64
Requesting MusicBrainz release 5305221f-104b-4d12-94dc-9527fd48418c
primary MB release type: single
Sending event: albuminfo_received
Candidate: Aimer - Ref:rain (TV size) (5305221f-104b-4d12-94dc-9527fd48418c)
Computing track assignment...
...done.
Success. Distance: 0.39
Querying VGMdb for release 72588
Querying VGMdb for release 72593
Querying VGMdb for release 72594
Logged from file vgmdb.py, line 43
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.15
Evaluating 6 candidates.

C:\Users\ME\Downloads\Muzik\[TESTOO]\[2018] (Koi wa Ameagari no You ni ED) Aimer - refrain_Mabayui bakari (眩いばかり)_SECL-2255~6\[2018] (Koi wa Ameagari no You ni ED) Aimer - refrain_Mabayui bakari (眩いばかり)_SECL-2255~6 (5 items)
Sending event: before_choose_candidate
Tagging:
    Aimer - Ref:rain / 眩いばかり
URL:
    https://musicbrainz.org/release/2877b5cf-4227-4a8c-a6b3-3318e2511c35
(Similarity: 96.2%) (unmatched tracks) (CD, 2018, JP, SME Records)
 * After Rain .Scarlet ver.- -> After Rain -Scarlet ver.-
Unmatched tracks (1):
 ! Ref:rain [TV size] (#5) (1:30)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? m
Finding tags for album "Aimer - Ref:rain / 眩いばかり".
Candidates:
1. Aimer - Ref:rain / 眩いばかり (96.2%) (unmatched tracks) (CD, 2018, JP, SME Records)
2. Aimer - Ref:rain / 眩いばかり (95.0%) (missing tracks) (2xCD, 2018, JP, SME Records)
3. Aimer - Ref:rain / 眩いばかり (86.9%) (tracks, missing tracks) (2xCD, 2018, JP, SME Records)
4. Aimer - Ref:rain / 眩いばかり (84.6%) (tracks, source, missing tracks) (Discogs, 2xCD, 2018, Taiwan, SME Records)
5. Aimer - Ref:rain (TV size) (61.4%) (unmatched tracks, album, tracks) (Digital Media, 2018, JP, SME Records)
6. Aimer - 花の唄 / ONE / 六等星の夜 Magic Blue ver. (36.5%) (tracks, album, year) (CD, 2017, JP, SME Records, 期間生産限定盤)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? e
Artist: Aimer
Album: ref:rain
Logged from file match.py, line 414
No album ID found.
Search terms: Aimer - ref:rain
Album might be VA: False
Searching for MusicBrainz releases with: {'release': u'ref:rain', 'tracks': u'5', 'artist': u'aimer'}
Requesting MusicBrainz release 5305221f-104b-4d12-94dc-9527fd48418c
primary MB release type: single
Sending event: albuminfo_received
Candidate: Aimer - Ref:rain (TV size) (5305221f-104b-4d12-94dc-9527fd48418c)
Computing track assignment...
...done.
Success. Distance: 0.39
Requesting MusicBrainz release 2877b5cf-4227-4a8c-a6b3-3318e2511c35
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.04
Requesting MusicBrainz release a7336cd0-3150-476b-a9fa-da1a7c083349
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.13
Requesting MusicBrainz release b80eb50a-5b4b-44d3-a931-292bf078aa5b
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.05
Requesting MusicBrainz release 58ec5e8a-4a84-4d5f-bf35-e179a8261760
primary MB release type: single
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.64
Querying VGMdb for release 72588
Querying VGMdb for release 72593
Querying VGMdb for release 72594
get_albums Querying VGMdb for release Aimer ref rain
Sending event: albuminfo_received
Candidate: Aimer - Ref:rain/Mabayui bakari / Aimer (72588)
Computing track assignment...
...done.
Success. Distance: 0.24
Sending event: albuminfo_received
Candidate: Aimer - Ref:rain/Mabayui bakari / Aimer [Limited Edition] (72593)
Computing track assignment...
...done.
Success. Distance: 0.31
Sending event: albuminfo_received
Candidate: Aimer - Ref:rain/Mabayui bakari / Aimer [Limited Edition] (72594)
Computing track assignment...
...done.
Success. Distance: 0.24
Sending event: albuminfo_received
Logged from file match.py, line 355
Computing track assignment...
...done.
Success. Distance: 0.15
Evaluating 9 candidates.
Sending event: before_choose_candidate
Tagging:
    Aimer - Ref:rain / 眩いばかり
URL:
    https://musicbrainz.org/release/2877b5cf-4227-4a8c-a6b3-3318e2511c35
(Similarity: 96.2%) (unmatched tracks) (CD, 2018, JP, SME Records)
 * After Rain .Scarlet ver.- -> After Rain -Scarlet ver.-
Unmatched tracks (1):
 ! Ref:rain [TV size] (#5) (1:30)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? m
Finding tags for album "Aimer - Ref:rain / 眩いばかり".
Candidates:
1. Aimer - Ref:rain / 眩いばかり (96.2%) (unmatched tracks) (CD, 2018, JP, SME Records)
2. Aimer - Ref:rain / 眩いばかり (95.0%) (missing tracks) (2xCD, 2018, JP, SME Records)
3. Aimer - Ref:rain / 眩いばかり (86.9%) (tracks, missing tracks) (2xCD, 2018, JP, SME Records)
4. Aimer - Ref:rain / 眩いばかり (84.6%) (tracks, source, missing tracks) (Discogs, 2xCD, 2018, Taiwan, SME Records)
5. Aimer - Ref:rain/Mabayui bakari / Aimer [Limited Edition] (76.5%) (source, album, missing tracks, ...) (VGMdb, 2xCD + DVD, 2018, JP, SME Records)
6. Aimer - Ref:rain/Mabayui bakari / Aimer (76.2%) (source, album, unmatched tracks, ...) (VGMdb, CD, 2018, JP, SME Records)
7. Aimer - Ref:rain/Mabayui bakari / Aimer [Limited Edition] (69.2%) (source, tracks, album, ...) (VGMdb, 2xCD + DVD, 2018, JP, SME Records)
8. Aimer - Ref:rain (TV size) (61.4%) (unmatched tracks, album, tracks) (Digital Media, 2018, JP, SME Records)
9. Aimer - 花の唄 / ONE / 六等星の夜 Magic Blue ver. (36.5%) (tracks, album, year) (CD, 2017, JP, SME Records, 期間生産限定盤)
# selection (default 1), Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? 5
Correcting tags from:
    Aimer - Ref:rain / 眩いばかり
To:
    Aimer - Ref:rain/Mabayui bakari / Aimer [Limited Edition]
URL:
    https://vgmdb.net/album/72594?perpage=99999
(Similarity: 76.5%) (source, album, missing tracks, tracks) (VGMdb, 2xCD + DVD, 2018, JP, SME Records)
CD + DVD 0
 * Ref:rain (#1)                  -> Ref:rain (#0-0)
 * 眩いばかり (#2)                     -> Mabayui bakari (#0-1) (title)
 * After Rain .Scarlet ver.- (#3) -> After Rain -Scarlet ver.- (#0-2)
 * Raining (#4)                   -> Raining (#0-3)
 * Ref:rain [TV size] (#5)        -> Ref:rain (TV Size) (#0-4)
Missing tracks (1/6 - 16.7%):
 ! "Koi wa Ameagari no You ni" Non-credit Ending Movie (#1-0) (1:41)
Apply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort, eDit, edit Candidates? a
Sending event: import_task_choice
Sending event: import_task_apply
0 of 5 items replaced
Sending event: database_change
Sending event: database_change
Traceback (most recent call last):
  File "C:\Python27\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.4.6', 'console_scripts', 'beet')()
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1256, in main
    _raw_main(args)
  File "c:\python27\lib\site-packages\beets\ui\__init__.py", line 1243, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 937, in import_func
    import_files(lib, paths, query)
  File "c:\python27\lib\site-packages\beets\ui\commands.py", line 914, in import_files
    session.run()
  File "c:\python27\lib\site-packages\beets\importer.py", line 327, in run
    pl.run_parallel(QUEUE_SIZE)
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "c:\python27\lib\site-packages\beets\util\pipeline.py", line 171, in coro
    task = func(*(args + (task,)))
  File "c:\python27\lib\site-packages\beets\importer.py", line 1415, in user_query
    apply_choice(session, task)
  File "c:\python27\lib\site-packages\beets\importer.py", line 1486, in apply_choice
    task.add(session.lib)
  File "c:\python27\lib\site-packages\beets\importer.py", line 751, in add
    self.album = lib.add_album(self.imported_items())
  File "c:\python27\lib\site-packages\beets\library.py", line 1324, in add_album
    item.add(self)
  File "c:\python27\lib\site-packages\beets\library.py", line 354, in add
    super(LibModel, self).add(lib)
  File "c:\python27\lib\site-packages\beets\dbcore\db.py", line 476, in add
    self.store()
  File "c:\python27\lib\site-packages\beets\library.py", line 346, in store
    super(LibModel, self).store(fields)
  File "c:\python27\lib\site-packages\beets\dbcore\db.py", line 405, in store
    tx.mutate(query, subvars)
  File "c:\python27\lib\site-packages\beets\dbcore\db.py", line 717, in mutate
    cursor = self.db._connection().execute(statement, subvals)
sqlite3.InterfaceError: Error binding parameter 25 - probably unsupported type.
```

I couldn't figure out what parameter 25 was, so I tried to query the db:

```
PS C:\Users\ME> beet -vv info aimer
user configuration: C:\Users\ME\AppData\Roaming\beets\config.yaml
data directory: C:\Users\ME\AppData\Roaming\beets
plugin paths: C:\Users\ME\AppData\Roaming\beets\beetsplug
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
inline: adding item field multidisc
Querying VGMdb
library database: C:\Users\ME\AppData\Roaming\beets\beets_musiclibrary.db
library directory: C:\Users\ME\Music
Sending event: library_opened
C:\Users\ME\Music\ZZ_NoAlbum\%Aimer\Ref_rain.mp3
          album: Ref:rain / 眩いばかり
       arranger:
            art: True
         artist: Aimer
  artist_credit: Aimer
    artist_sort: Aimer
       bitdepth: 0
        bitrate: 320000
            bpm: 0
       channels: 2
       comments: 
           comp: False
           date: 2018-01-01
           disc: 0
      disctotal: 0
         format: MP3
          genre: J-Pop
         genres: J-Pop
         length: 290.146666667
         lyrics: 
    mb_artistid: 9388cee2-7d57-4598-905f-106019b267d3
     mb_trackid: 39f205b9-d9f9-491e-8959-bc7b970515d7
  original_year: 0
r128_album_gain: 0
r128_track_gain: 0
     samplerate: 44100
          title: Ref:rain
          track: 1
     tracktotal: 5
           year: 2018

C:\Users\ME\Music\ZZ_NoAlbum\%Aimer\Xuan ibakari.mp3
          album: Ref:rain / 眩いばかり
       arranger:
            art: True
         artist: Aimer
  artist_credit: Aimer
    artist_sort: Aimer
       bitdepth: 0
        bitrate: 320000
            bpm: 0
       channels: 2
       comments: 
           comp: False
           date: 2018-01-01
           disc: 0
      disctotal: 0
         format: MP3
          genre: J-Pop
         genres: J-Pop
         length: 251.386666667
         lyrics:
    mb_artistid: 9388cee2-7d57-4598-905f-106019b267d3
     mb_trackid: 7946e8a6-f73a-4338-966b-afe124c2b9d4
  original_year: 0
r128_album_gain: 0
r128_track_gain: 0
     samplerate: 44100
          title: 眩いばかり
          track: 2
     tracktotal: 5
           year: 2018

C:\Users\ME\Music\ZZ_NoAlbum\%Aimer\After Rain -Scarlet ver.-.mp3
          album: Ref:rain / 眩いばかり
       arranger:
            art: True
         artist: Aimer
  artist_credit: Aimer
    artist_sort: Aimer
       bitdepth: 0
        bitrate: 320000
            bpm: 0
       channels: 2
       comments: 
           comp: False
           date: 2018-01-01
           disc: 0
      disctotal: 0
         format: MP3
          genre: J-Pop
         genres: J-Pop
         length: 301.76
         lyrics:
    mb_artistid: 9388cee2-7d57-4598-905f-106019b267d3
     mb_trackid: 0b9f9ed9-706b-4e25-a651-40ddecb6add2
  original_year: 0
r128_album_gain: 0
r128_track_gain: 0
     samplerate: 44100
          title: After Rain -Scarlet ver.-
          track: 3
     tracktotal: 5
           year: 2018

C:\Users\ME\Music\ZZ_NoAlbum\%Aimer\Raining.mp3
          album: Ref:rain / 眩いばかり
       arranger:
            art: True
         artist: Aimer
  artist_credit: Aimer
    artist_sort: Aimer
       bitdepth: 0
        bitrate: 320000
            bpm: 0
       channels: 2
       comments: 
           comp: False
           date: 2018-01-01
           disc: 0
      disctotal: 0
         format: MP3
          genre: J-Pop
         genres: J-Pop
         length: 306.56
         lyrics:
    mb_artistid: 9388cee2-7d57-4598-905f-106019b267d3
     mb_trackid: 31d26e99-320f-40c5-aea0-c2f1ab10b17f
  original_year: 0
r128_album_gain: 0
r128_track_gain: 0
     samplerate: 44100
          title: Raining
          track: 4
     tracktotal: 5
           year: 2018

C:\Users\ME\Music\ZZ_NoAlbum\%Aimer\Ref_rain (TV size).mp3
          album: Ref:rain / 眩いばかり
       arranger:
            art: True
         artist: Aimer
  artist_credit: Aimer
    artist_sort: Aimer
       bitdepth: 0
        bitrate: 320000
            bpm: 0
       channels: 2
       comments: 
           comp: False
           date: 2018-01-01
           disc: 0
      disctotal: 0
         format: MP3
          genre: J-Pop
         genres: J-Pop
         length: 90.68
         lyrics: 
    mb_artistid: 9388cee2-7d57-4598-905f-106019b267d3
     mb_trackid: 5bb14407-1b94-4022-b2ba-9a7898581936
  original_year: 0
r128_album_gain: 0
r128_track_gain: 0
     samplerate: 44100
          title: Ref:rain (TV size)
          track: 5
     tracktotal: 5
           year: 2018
```

### Setup
- Win7x64
- Python: 2.7.14 / Beets: 1.4.6

Config.yaml

```
### Global Options
directory: ~/Music
library: beets_musiclibrary.db
ignore_hidden: yes
asciify_paths: no
terminal_encoding: "utf-8" #'utf_8'
# terminal_encoding: "cp65001"

art_filename: %asciify{cover_$album}
max_filename_length: 0 #unlimited
path_sep_replace: _
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

threaded: yes
timeout: 5.0
verbose: 0

original_date: no
per_disc_numbering: yes

va_name: "Various Artists"
artist_credit: no
id3v23: no

format_item: $artist - $album - $title
format_album: $albumartist - $album
time_format: '%Y-%m-%d %H:%M:%S'
format_raw_length: no

sort_album: albumartist+ album+
sort_item: artist+ album+ disc+ track+
sort_case_insensitive: yes

### Import Options
import:
    log: ~/beets-import.log
    write: yes # write metadata to music files
    copy: yes # move imported files from src to the music dir

    group_albums: no
    pretend: false
    search_ids: []
    duplicate_action: ask
    bell: no
    set_fields: {}

    autotag: yes
    timid: no # do not require confirmation on strong matches

    resume: ask
    incremental: no
    incremental_skip_later: no

    quiet_fallback: skip
    none_rec_action: ask
    default_action: apply
    singletons: no
    languages: [] # ISO 639-1 or ISO 639-2?
    detail: no
    flat: no

### Plugin Options
pluginpath: [
  ~\AppData\Roaming\beets\beetsplug,
]

plugins: [
  vgmdb,
  discogs,
  lyrics,
  embedart,
  fetchart,
  lastgenre,
  scrub,
  ftintitle,
  metasync,
  edit,
  fromfilename,
  bucket,
  inline,
  the,
  badfiles,
  missing,
  info,
  duplicates
]

lyrics:
    auto: yes

lastgenre:
    auto: yes
    source: artist

fetchart:
    auto: yes
    minwidth: 500
    maxwidth: 2000
    cautious: yes
    cover_names: cover cvr folder album
    sources: filesystem coverart amazon itunes albumart

embedart:
    auto: yes

scrub:
    auto: no

# Move "featured" artists from artist field to title
ftintitle:
    auto: yes

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

# Inline plugin multidisc template
item_fields:
    multidisc: 1 if disctotal > 1 else 0

### Path options
bucket:
    bucket_alpha: ['0-9', 'A-D', 'E-H', 'I-L', 'M-P', 'Q-U', 'V-Z']

paths:
    ## A-D/Artist, The/[YEAR] Album Name, The/1-01. Track Name.mp3
    default: '%bucket{%upper{%left{%the{$albumartist},1}}}/%the{$albumartist}/[%if{$year,$year,0000}] $album %aunique{}/%if{$multidisc,$disc-}$track. $title'

    ## ZZ_NoAlbum/Artist, The - Track Name.mp3
    singleton: ZZ_NoAlbum/%%the{$artist}/%asciify{$title}

### UI Options
ui:
    terminal_width: 80
    length_diff_thresh: 10.0
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

### AutoTagger
match:
    strong_rec_thresh: 0.04 #0.1, match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    required: []
    track_length_grace: 10
    track_length_max: 30
```
